import json, os
from http.server import BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs
import sys; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _helpers import get_token

META_INCOMPAT = [
    # Audience não combina com placement (doc oficial Meta)
    ["audience","placement"],
    # Audience não combina com region quando juntos com placement
    ["audience","region"],
    # Lead form não combina com audience
    ["lead","audience"],
    # Lead form não combina com placement
    ["lead","placement"],
    # Lead form não combina com region
    ["lead","region"],
    # Lead form não combina com ad level
    ["lead","ad"],
]

META_DIMENSIONS = [
    {"id":"date_start","label":"Date"},
    {"id":"account_id","label":"Account ID"},{"id":"account_name","label":"Account name"},
    {"id":"campaign_id","label":"Campaign ID"},{"id":"campaign_name","label":"Campaign name"},
    {"id":"adset_id","label":"Ad set ID"},{"id":"adset_name","label":"Ad set name"},
    {"id":"ad_id","label":"Ad ID","group":"ad"},{"id":"ad_name","label":"Ad name","group":"ad"},
    {"id":"ad_creative_id","label":"Ad creative ID","group":"ad"},{"id":"ad_creative_name","label":"Ad creative name","group":"ad"},
    {"id":"ad_title","label":"Ad title","group":"ad"},{"id":"ad_body","label":"Ad body","group":"ad"},
    {"id":"object_type","label":"Object type","group":"ad"},{"id":"call_to_action_type","label":"Call-to-action type","group":"ad"},
    {"id":"image_url","label":"Ad creative image URL","group":"ad"},
    {"id":"url_tags","label":"URL tags (utm)","group":"ad"},
    {"id":"post_id","label":"Post ID"},{"id":"post_type","label":"Post type"},
    {"id":"page_id","label":"Page ID"},{"id":"page_name","label":"Page name"},
    {"id":"product_id","label":"Product ID"},
    {"id":"lead_form_id","label":"Lead form ID","group":"lead"},{"id":"lead_form_name","label":"Lead form name","group":"lead"},
    {"id":"ad_status","label":"Ad status"},{"id":"adset_status","label":"Ad set status"},{"id":"campaign_status","label":"Campaign status"},
    {"id":"campaign_objective","label":"Campaign objective"},{"id":"campaign_buying_type","label":"Campaign buying type"},
    {"id":"bid_type","label":"Bid type"},{"id":"bid_amount","label":"Bid amount"},{"id":"bid_strategy","label":"Bid strategy"},
    {"id":"optimization_goal","label":"Ad set optimization goal"},
    {"id":"daily_budget","label":"Daily budget"},{"id":"lifetime_budget","label":"Lifetime budget"},
    {"id":"targeting","label":"Targeting"},
    {"id":"targeting_age_min","label":"Targeting minimum age"},{"id":"targeting_age_max","label":"Targeting maximum age"},
    {"id":"targeting_country","label":"Targeting country location"},
    {"id":"data_source","label":"Data source"},{"id":"business_name","label":"Business name"},
    {"id":"destination_url","label":"Destination URL"},
    {"id":"promoted_post_url","label":"Promoted post destination URL"},
    {"id":"external_destination_url","label":"External destination URL"},
    {"id":"day_of_week","label":"Day of week"},
    {"id":"year","label":"Year"},{"id":"month","label":"Month"},{"id":"quarter","label":"Quarter"},
    {"id":"hour","label":"Hour"},{"id":"year_month","label":"Year & month"},
    {"id":"age","label":"Age","group":"audience"},{"id":"gender","label":"Gender","group":"audience"},
    {"id":"country","label":"Country","group":"region"},{"id":"country_code","label":"Country code","group":"region"},
    {"id":"region","label":"Region","group":"region"},
    {"id":"publisher_platform","label":"Publisher platform","group":"placement"},
    {"id":"platform_position","label":"Platform position","group":"placement"},
    {"id":"impression_device","label":"Impression device","group":"placement"},
    {"id":"device_platform","label":"Device platform","group":"placement"},
    {"id":"placement","label":"Placement","group":"placement"},
    {"id":"attribution_setting","label":"Attribution setting"},
    {"id":"action_type","label":"Action type"},
    {"id":"quality_ranking","label":"Quality ranking"},
    {"id":"engagement_rate_ranking","label":"Engagement Rate Ranking"},
    {"id":"conversion_rate_ranking","label":"Conversion Rate Ranking"},
]

META_METRICS = [
    # Core performance
    {"id":"impressions","label":"Impressions"},{"id":"reach","label":"Reach"},
    {"id":"frequency","label":"Frequency"},{"id":"spend","label":"Amount spent"},
    {"id":"cpm","label":"CPM"},{"id":"cpc","label":"CPC (link)"},
    {"id":"ctr","label":"CTR (link click-through rate)"},{"id":"unique_ctr","label":"Unique CTR (link)"},
    {"id":"cpp","label":"Cost per 1000 people reached"},
    {"id":"clicks","label":"Clicks (all)"},{"id":"unique_clicks","label":"Unique clicks (all)"},
    {"id":"inline_link_clicks","label":"Link clicks"},{"id":"unique_inline_link_clicks","label":"Unique link clicks"},
    {"id":"inline_post_engagement","label":"Inline post engagement"},
    {"id":"cost_per_unique_click","label":"Cost per unique click (all)"},
    {"id":"cost_per_inline_link_click","label":"CPC (link)"},
    {"id":"outbound_clicks","label":"Outbound clicks"},{"id":"unique_outbound_clicks","label":"Unique outbound clicks"},
    {"id":"outbound_clicks_ctr","label":"Outbound CTR"},{"id":"unique_outbound_clicks_ctr","label":"Unique outbound CTR"},
    {"id":"cost_per_outbound_click","label":"Cost per outbound click"},
    {"id":"cost_per_unique_outbound_click","label":"Cost per unique outbound click"},
    {"id":"landing_page_views","label":"Landing page views"},
    {"id":"unique_landing_page_views","label":"Unique landing page views"},
    {"id":"cost_per_landing_page_view","label":"Cost per landing page view"},
    {"id":"deeplink_clicks","label":"Deeplink clicks"},
    {"id":"app_store_clicks","label":"App store clicks"},
    {"id":"social_spend","label":"Social spend"},
    {"id":"total_action_value","label":"Total action value"},
    {"id":"cost_per_any_action","label":"Cost per any action"},
    # Spend by currency
    {"id":"spend_eur","label":"Amount spent (EUR)"},{"id":"spend_gbp","label":"Amount spent (GBP)"},
    {"id":"spend_usd","label":"Amount spent (USD)"},{"id":"spend_sek","label":"Amount spent (SEK)"},
    # Engagement
    {"id":"page_engagement","label":"Page engagements"},{"id":"post_engagement","label":"Post engagements"},
    {"id":"page_likes","label":"Page likes"},{"id":"page_subscribed","label":"Page subscribes"},
    {"id":"post_reactions","label":"Post reactions"},{"id":"post_comments","label":"Post comments"},
    {"id":"post_saves","label":"Post saves"},{"id":"post_shares","label":"Post shares"},
    {"id":"photo_view","label":"Photo views"},{"id":"event_responses","label":"Event responses"},
    {"id":"checkin","label":"Check-ins"},
    {"id":"unique_page_engagements","label":"Unique page engagements"},
    {"id":"unique_page_likes","label":"Unique page likes"},
    {"id":"unique_post_comments","label":"Unique post comments"},
    {"id":"unique_post_engagements","label":"Unique post engagements"},
    {"id":"unique_post_reactions","label":"Unique post reactions"},
    {"id":"unique_post_shares","label":"Unique post shares"},
    {"id":"unique_photo_views","label":"Unique photo views"},
    {"id":"unique_event_responses","label":"Unique event responses"},
    {"id":"unique_checkins","label":"Unique check-ins"},
    {"id":"cost_per_page_engagement","label":"Cost per page engagement"},
    {"id":"cost_per_page_like","label":"Cost per page like"},
    {"id":"cost_per_post_comment","label":"Cost per post comment"},
    {"id":"cost_per_post_engagement","label":"Cost per post engagement"},
    {"id":"cost_per_post_reaction","label":"Cost per post reaction"},
    {"id":"cost_per_post_share","label":"Cost per post share"},
    {"id":"cost_per_photo_view","label":"Cost per photo view"},
    {"id":"cost_per_event_response","label":"Cost per event response"},
    {"id":"cost_per_checkin","label":"Cost per check-in"},
    {"id":"cost_per_unique_link_click","label":"Cost per unique link click"},
    # Messaging
    {"id":"messaging_conversations_started","label":"Messaging conversations started"},
    {"id":"cost_per_messaging_conversation","label":"Cost per messaging conversations started"},
    {"id":"cost_per_new_messaging_contact","label":"Cost per new messaging contact"},
    {"id":"messaging_replies","label":"Messaging replies"},
    {"id":"messaging_reply_rate","label":"Messaging reply rate"},
    {"id":"cost_per_messaging_reply","label":"Cost per messaging reply"},
    {"id":"new_messaging_contacts","label":"New messaging contacts"},
    {"id":"blocked_messaging_conversations","label":"Blocked messaging conversations"},
    # Video
    {"id":"video_view","label":"3-second video views"},
    {"id":"unique_video_view_3s","label":"3-second video views (unique)"},
    {"id":"video_continuous_2_sec_watched_actions","label":"2-second continuous video views"},
    {"id":"ten_sec_video_view","label":"10-second video views"},
    {"id":"video_30_sec_watched_actions","label":"30-second video views"},
    {"id":"video_15_sec_watched_actions","label":"15-second video views (Deprecated)"},
    {"id":"video_p25_watched_actions","label":"Video watches at 25%"},
    {"id":"video_p50_watched_actions","label":"Video watches at 50%"},
    {"id":"video_p75_watched_actions","label":"Video watches at 75%"},
    {"id":"video_p95_watched_actions","label":"Video watches at 95%"},
    {"id":"video_p100_watched_actions","label":"Video watches at 100%"},
    {"id":"video_avg_time_watched_actions","label":"Video average watch time"},
    {"id":"video_avg_pct_watched_actions","label":"Video average percentage watched"},
    {"id":"video_play_actions","label":"Clicks to play video"},
    {"id":"video_thruplay_watched_actions","label":"ThruPlay actions"},
    {"id":"canvas_avg_view_time","label":"Avg. canvas view time"},
    {"id":"canvas_avg_view_percent","label":"Avg. canvas view percentage"},
    {"id":"cost_per_3s_video_view","label":"Cost per three-second video view"},
    {"id":"cost_per_2s_continuous_video_view","label":"Cost per 2-second continuous video play"},
    {"id":"cost_per_10s_video_view","label":"Cost per ten-second video view"},
    {"id":"cost_per_thruplay","label":"Cost per ThruPlay"},
    # Video play curve
    {"id":"video_play_curve_0","label":"Video play curve: 0s"},{"id":"video_play_curve_1","label":"Video play curve: 1s"},
    {"id":"video_play_curve_2","label":"Video play curve: 2s"},{"id":"video_play_curve_3","label":"Video play curve: 3s"},
    {"id":"video_play_curve_4","label":"Video play curve: 4s"},{"id":"video_play_curve_5","label":"Video play curve: 5s"},
    {"id":"video_play_curve_6","label":"Video play curve: 6s"},{"id":"video_play_curve_7","label":"Video play curve: 7s"},
    {"id":"video_play_curve_10","label":"Video play curve: 10s"},
    {"id":"video_play_curve_15_20","label":"Video play curve: 15-20s"},
    {"id":"video_play_curve_20_25","label":"Video play curve: 20-25s"},
    {"id":"video_play_curve_25_30","label":"Video play curve: 25-30s"},
    {"id":"video_play_curve_30_40","label":"Video play curve: 30-40s"},
    {"id":"video_play_curve_40_50","label":"Video play curve: 40-50s"},
    {"id":"video_play_curve_50_60","label":"Video play curve: 50-60s"},
    {"id":"video_play_curve_60plus","label":"Video play curve: 60s+"},
    # Brand awareness
    {"id":"estimated_ad_recallers","label":"Estimated ad recall lift (people)"},
    {"id":"estimated_ad_recall_rate","label":"Estimated ad recall lift rate (%)"},
    {"id":"cost_per_estimated_ad_recallers","label":"Cost per estimated ad recall lift"},
    # Conversions general
    {"id":"actions","label":"Actions"},{"id":"unique_actions","label":"Unique actions"},
    {"id":"unique_conversions","label":"Unique conversions"},
    {"id":"conversions_1d_view","label":"Conversions within 1 day of view"},
    {"id":"conversions_7d_view","label":"Conversions within 7 days of view"},
    {"id":"conversions_28d_view","label":"Conversions within 28 days of view"},
    {"id":"conversions_1d_click","label":"Conversions within 1 day of click"},
    {"id":"conversions_7d_click","label":"Conversions within 7 days of click"},
    {"id":"conversions_28d_click","label":"Conversions within 28 days of click"},
    {"id":"conversion_value_1d_view","label":"Conversion value within 1 day of view"},
    {"id":"conversion_value_7d_view","label":"Conversion value within 7 days of view"},
    {"id":"conversion_value_28d_view","label":"Conversion value within 28 days of view"},
    {"id":"conversion_value_1d_click","label":"Conversion value within 1 day of click"},
    {"id":"conversion_value_7d_click","label":"Conversion value within 7 days of click"},
    {"id":"conversion_value_28d_click","label":"Conversion value within 28 days of click"},
    # Purchases
    {"id":"purchase","label":"Purchases"},{"id":"unique_purchases","label":"Unique purchases"},
    {"id":"purchase_value","label":"Purchase conversion value"},{"id":"cost_per_purchase","label":"Cost per purchase"},
    {"id":"website_purchase_roas","label":"Website purchase ROAS"},
    {"id":"omni_purchases","label":"Omni purchases"},{"id":"omni_purchase_roas","label":"Omni purchase ROAS"},
    {"id":"return_on_ad_spend","label":"Return on ad spend (ROAS)"},
    # Website conversions
    {"id":"website_purchases","label":"Website purchases"},{"id":"website_purchase_value","label":"Website purchases conversion value"},
    {"id":"cost_per_website_purchase","label":"Cost per website purchase"},
    {"id":"website_adds_to_cart","label":"Website adds to cart"},{"id":"website_adds_to_cart_value","label":"Website adds to cart conversion value"},
    {"id":"cost_per_website_add_to_cart","label":"Cost per website add to cart"},
    {"id":"website_checkouts","label":"Website checkouts initiated"},{"id":"website_checkouts_value","label":"Website checkouts initiated conversion value"},
    {"id":"cost_per_website_checkout","label":"Cost per website checkout initiated"},
    {"id":"website_leads","label":"Website leads"},{"id":"website_leads_value","label":"Website leads conversion value"},
    {"id":"cost_per_website_lead","label":"Cost per website lead"},
    {"id":"website_registrations","label":"Website registrations completed"},
    {"id":"website_content_views","label":"Website content views"},
    {"id":"website_searches","label":"Website searches"},
    {"id":"website_adds_to_wishlist","label":"Website adds to wishlist"},
    {"id":"website_payment_info_adds","label":"Website adds of payment info"},
    {"id":"website_custom_conversions","label":"Website custom conversions"},
    {"id":"cost_per_website_conversion","label":"Cost per website conversion"},
    {"id":"website_conversion_value","label":"Website conversion value"},
    {"id":"website_conversion_rate","label":"Website conversion rate"},
    # On-Facebook
    {"id":"onsite_purchases","label":"On-Facebook purchases"},
    {"id":"onsite_purchase_value","label":"Conversion value of purchase on Facebook"},
    {"id":"cost_per_onsite_purchase","label":"Cost per on-Facebook purchase"},
    {"id":"onsite_leads","label":"On-Facebook leads"},
    {"id":"onsite_view_content","label":"On-Facebook view content"},
    {"id":"onsite_workflow_completion","label":"On-Facebook workflow completion"},
    {"id":"phone_clicks","label":"Phone number clicks"},{"id":"get_directions_clicks","label":"Get directions clicks"},
    # Leads
    {"id":"leads","label":"Leads"},{"id":"unique_leads","label":"Unique leads"},
    {"id":"leads_form","label":"Leads (form)"},{"id":"unique_leads_form","label":"Unique leads (form)"},
    {"id":"cost_per_lead","label":"Cost per lead"},{"id":"cost_per_lead_form","label":"Cost per lead (form)"},
    # Cart/Checkout
    {"id":"adds_to_cart","label":"Adds to cart"},{"id":"unique_adds_to_cart","label":"Unique adds to cart"},
    {"id":"initiated_checkouts","label":"Checkouts initiated"},
    {"id":"payment_info_adds","label":"Payment info adds"},
    {"id":"adds_to_wishlist","label":"Adds to wishlist"},
    {"id":"content_views","label":"Content views"},
    {"id":"searches","label":"Searches"},
    {"id":"complete_registration","label":"Registrations completed"},
    # Subscriptions
    {"id":"subscribes","label":"Subscribes"},{"id":"start_trial","label":"Trials started"},
    {"id":"contact_total","label":"Contact (total)"},{"id":"cost_per_contact","label":"Cost per Contact"},
    {"id":"donate_total","label":"Donate (total)"},{"id":"cost_per_donate","label":"Cost per Donate"},
    {"id":"find_location_total","label":"Find location (total)"},{"id":"cost_per_find_location","label":"Cost per Find location"},
    {"id":"schedule_total","label":"Schedule (total)"},{"id":"cost_per_schedule","label":"Cost per Schedule"},
    {"id":"submit_application_total","label":"Submit application (total)"},{"id":"cost_per_submit_application","label":"Cost per Submit application"},
    {"id":"customize_product_total","label":"Customize product (total)"},{"id":"cost_per_customize_product","label":"Cost per Customize product"},
    {"id":"cost_per_subscribe","label":"Cost per Subscribe"},{"id":"cost_per_start_trial","label":"Cost per Start trial"},
    # Mobile app
    {"id":"mobile_app_installs","label":"Mobile app installs"},
    {"id":"cost_per_mobile_app_install","label":"Cost per mobile app install"},{"id":"cost_per_app_install","label":"Cost per app install"},
    {"id":"mobile_app_purchases","label":"Mobile app purchases"},
    {"id":"mobile_app_purchase_roas","label":"Mobile app purchase ROAS"},
    {"id":"mobile_app_adds_to_cart","label":"Mobile app adds to cart"},
    {"id":"mobile_app_checkouts","label":"Mobile app checkouts initiated"},
    {"id":"mobile_app_registrations","label":"Mobile app registrations completed"},
    {"id":"mobile_app_content_views","label":"Mobile app content views"},
    {"id":"mobile_app_searches","label":"Mobile app searches"},
    {"id":"mobile_app_sessions","label":"Mobile app sessions"},
    {"id":"mobile_app_credits_spent","label":"Mobile app credits spent"},
    {"id":"mobile_app_tutorials","label":"Mobile app tutorials completed"},
    {"id":"mobile_app_achievements","label":"Mobile app achievements unlocked"},
    {"id":"mobile_app_levels","label":"Mobile app levels completed"},
    {"id":"mobile_app_ratings","label":"Mobile app ratings submitted"},
    {"id":"mobile_app_adds_to_wishlist","label":"Mobile app adds to wishlist"},
    {"id":"mobile_app_payment_info","label":"Mobile app adds of payment info"},
    {"id":"cost_per_mobile_app_purchase","label":"Cost per mobile app purchase"},
    {"id":"cost_per_mobile_app_action","label":"Cost per mobile app action"},
    # Omni
    {"id":"omni_adds_to_cart","label":"Omni adds to cart"},{"id":"omni_searches","label":"Omni searches"},
    {"id":"omni_content_views","label":"Omni content views"},{"id":"omni_registrations","label":"Omni completed registrations"},
    {"id":"omni_checkouts","label":"Omni initiated checkouts"},{"id":"omni_custom_actions","label":"Omni custom actions"},
    # Offline
    {"id":"offline_purchases","label":"Offline purchases"},{"id":"offline_purchase_value","label":"Offline purchases conversion value"},
    {"id":"offline_adds_to_cart","label":"Offline adds to cart"},
    {"id":"offline_leads","label":"Offline leads"},
    {"id":"offline_registrations","label":"Offline registrations completed"},
    {"id":"offline_checkouts","label":"Offline checkouts initiated"},
    {"id":"offline_content_views","label":"Offline content views"},
    {"id":"offline_searches","label":"Offline searches"},
    {"id":"offline_adds_to_wishlist","label":"Offline adds to wishlist"},
    {"id":"offline_payment_info","label":"Offline adds of payment info"},
    # Store visits
    {"id":"store_visits_low","label":"Store visits low estimate"},
    {"id":"store_visits_point","label":"Store visits point estimate"},
    {"id":"store_visits_high","label":"Store visits high estimate"},
    {"id":"cost_per_store_visit","label":"Cost per store visit"},
    # Quality/ranking
    {"id":"quality_ranking","label":"Quality ranking"},
    {"id":"engagement_rate_ranking","label":"Engagement Rate Ranking"},
    {"id":"conversion_rate_ranking","label":"Conversion Rate Ranking"},
    {"id":"relevance_score","label":"Relevance score"},
    {"id":"people_taking_action","label":"People taking action"},
    {"id":"people_taking_action_rate","label":"People taking action rate %"},
]

TIKTOK_INCOMPAT = [
    # Audience não combina com ad level (Basic report)
    ["audience","ad"],
    # Audience não combina com geo detalhado
    ["audience","geo"],
    # Audience não combina com placement no mesmo breakdown
    ["audience","placement"],
    # TrueView/YouTube específico — não mistura com padrão
    ["trueview","standard"],
]

TIKTOK_DIMENSIONS = [
    {"id":"stat_time_day","label":"Date"},{"id":"hour","label":"Hour"},
    {"id":"year","label":"Year"},{"id":"month","label":"Month"},
    {"id":"day_of_week","label":"Day of week"},{"id":"year_month","label":"Year & month"},
    {"id":"advertiser_id","label":"Advertiser ID"},{"id":"advertiser_name","label":"Advertiser name"},
    {"id":"campaign_id","label":"Campaign ID"},{"id":"campaign_name","label":"Campaign name"},
    {"id":"campaign_status","label":"Campaign status"},
    {"id":"campaign_objective_type","label":"Campaign objective type"},
    {"id":"campaign_budget","label":"Campaign budget"},{"id":"campaign_type","label":"Campaign type"},
    {"id":"campaign_creation_date","label":"Campaign creation date"},
    {"id":"adgroup_id","label":"Ad group ID","group":"adgroup"},
    {"id":"adgroup_name","label":"Ad group name","group":"adgroup"},
    {"id":"adgroup_status","label":"Ad group status","group":"adgroup"},
    {"id":"optimization_goal","label":"Optimization goal","group":"adgroup"},
    {"id":"bid_method","label":"Bid method","group":"adgroup"},
    {"id":"bidding_strategy","label":"Bidding strategy","group":"adgroup"},
    {"id":"pacing","label":"Pacing","group":"adgroup"},
    {"id":"schedule_type","label":"Schedule type","group":"adgroup"},
    {"id":"placement_type","label":"Placement type","group":"adgroup"},
    {"id":"ad_group_budget","label":"Ad group budget","group":"adgroup"},
    {"id":"ad_id","label":"Ad ID","group":"ad"},{"id":"ad_name","label":"Ad name","group":"ad"},
    {"id":"ad_status","label":"Ad status","group":"ad"},
    {"id":"ad_text","label":"Ad text","group":"ad"},
    {"id":"display_name","label":"Display name","group":"ad"},
    {"id":"call_to_action","label":"Call-to-action","group":"ad"},
    {"id":"video_id","label":"Video ID","group":"ad"},
    {"id":"image_mode","label":"Image mode","group":"ad"},
    {"id":"creative_format","label":"Creative format","group":"ad"},
    {"id":"landing_page_url","label":"Landing page URL","group":"ad"},
    {"id":"profile_image_url","label":"Profile image URL","group":"ad"},
    {"id":"video_thumbnail_url","label":"Video thumbnail URL","group":"ad"},
    {"id":"post_id","label":"Post ID","group":"ad"},
    {"id":"utm_source","label":"utm_source parameter value","group":"ad"},
    {"id":"utm_medium","label":"utm_medium parameter value","group":"ad"},
    {"id":"utm_campaign","label":"utm_campaign parameter value","group":"ad"},
    {"id":"age","label":"Age","group":"audience"},{"id":"gender","label":"Gender","group":"audience"},
    {"id":"language","label":"Language","group":"audience"},
    {"id":"interest_category","label":"Interest category","group":"audience"},
    {"id":"audience_type","label":"Audience type","group":"audience"},
    {"id":"age_targeting","label":"Age targeting","group":"audience"},
    {"id":"gender_targeting","label":"Gender targeting","group":"audience"},
    {"id":"operating_system","label":"Operating system targeting","group":"audience"},
    {"id":"connection_type","label":"Connection type","group":"audience"},
    {"id":"country_code","label":"Country code","group":"geo"},
    {"id":"country","label":"Country","group":"geo"},
    {"id":"province_id","label":"Province ID","group":"geo"},
    {"id":"province_name","label":"Province name","group":"geo"},
    {"id":"dma_id","label":"DMA ID","group":"geo"},{"id":"dma_name","label":"DMA name","group":"geo"},
    {"id":"device_platform","label":"Device platform","group":"device"},
    {"id":"placement","label":"Placement","group":"placement"},
    {"id":"ag_placement","label":"AG Placement","group":"placement"},
    {"id":"pixel_id","label":"Pixel ID"},{"id":"conversion_event","label":"Conversion event"},
    {"id":"promoted_app_name","label":"Promoted app name"},
    {"id":"promoted_app_id","label":"Promoted app ID"},
    {"id":"mobile_app_id","label":"Mobile app ID"},
    {"id":"business_center_id","label":"Business center ID"},
    {"id":"business_center_name","label":"Business center name"},
    {"id":"advertiser_country","label":"Advertiser country"},
    {"id":"advertiser_timezone","label":"Time zone"},
    {"id":"advertiser_currency","label":"Currency"},
]

TIKTOK_METRICS = [
    # Core
    {"id":"impressions","label":"Impressions"},{"id":"reach","label":"Reach"},
    {"id":"frequency","label":"Frequency"},{"id":"spend","label":"Cost"},
    {"id":"cpm","label":"CPM"},{"id":"cpc","label":"CPC"},{"id":"ctr","label":"CTR"},
    {"id":"clicks","label":"Clicks"},{"id":"clicks_all","label":"Clicks (All)"},
    {"id":"cost_per_1000_reached","label":"Cost per 1,000 people reached"},
    {"id":"result","label":"Results"},{"id":"result_rate","label":"Result rate"},
    {"id":"cost_per_result","label":"Cost per result"},
    {"id":"conversion","label":"Conversions"},{"id":"conversion_rate","label":"Conversion rate"},
    {"id":"cost_per_conversion","label":"Cost per conversion"},
    {"id":"real_time_result","label":"Real-time results"},
    {"id":"real_time_result_rate","label":"Real-time result rate"},
    {"id":"cost_per_real_time_result","label":"Cost per real-time result"},
    {"id":"real_time_conversion","label":"Real-time conversions"},
    {"id":"real_time_conversion_rate","label":"Real-time conversion rate"},
    {"id":"cost_per_real_time_conversion","label":"Cost per real-time conversion"},
    {"id":"secondary_goal_result","label":"Secondary goal result"},
    {"id":"cost_per_secondary_goal_result","label":"Cost per secondary goal result"},
    # Video
    {"id":"video_play_actions","label":"Video views"},
    {"id":"video_watched_2s","label":"2-second video views"},
    {"id":"video_watched_6s","label":"6-second video views (focused view)"},
    {"id":"video_watched_15s","label":"15-second video views (focused view)"},
    {"id":"video_views_p25","label":"Video views at 25%"},
    {"id":"video_views_p50","label":"Video views at 50%"},
    {"id":"video_views_p75","label":"Video views at 75%"},
    {"id":"video_views_p100","label":"Video views at 100%"},
    {"id":"average_video_play","label":"Avg watch time per video view"},
    {"id":"average_video_play_per_user","label":"Avg watch time per person"},
    # Engagement
    {"id":"profile_visits","label":"Profile visits"},
    {"id":"likes","label":"Paid likes"},{"id":"comments","label":"Paid comments"},
    {"id":"shares","label":"Paid shares"},{"id":"follows","label":"Paid follows"},
    {"id":"sound_clicks","label":"Sound clicks"},
    {"id":"use_sound_button_clicks","label":"Use sound button clicks"},
    {"id":"duet_clicks","label":"Duet clicks"},{"id":"stitch_clicks","label":"Stitch clicks"},
    {"id":"gmv_max_ads_spend","label":"GMV Max Ads spend"},
    {"id":"gmv_max_ads_billed_cost","label":"GMV Max Ads billed cost"},
    # Landing page / website
    {"id":"total_landing_page_view","label":"Total landing page view"},
    {"id":"cost_per_landing_page_view","label":"Cost per landing page view"},
    {"id":"landing_page_view_rate","label":"Landing page view rate"},
    {"id":"page_views_website","label":"Page views (website)"},
    # Conversions - website
    {"id":"complete_payment_roas","label":"Complete payment ROAS"},
    {"id":"complete_payment","label":"Complete payment events"},
    {"id":"total_complete_payment_value","label":"Total complete payment value"},
    {"id":"add_to_cart_events","label":"Add to cart events"},
    {"id":"total_add_to_cart_value","label":"Total add to cart value"},
    {"id":"cost_per_add_to_cart","label":"Cost per add to cart"},
    {"id":"checkout_initiations","label":"Checkout initiations"},
    {"id":"total_initiate_checkout_value","label":"Total initiate checkout value"},
    {"id":"form_submissions","label":"Form submissions"},
    {"id":"total_form_submission_value","label":"Total form submission value"},
    {"id":"user_registrations","label":"User registrations"},
    {"id":"total_user_registration_value","label":"Total user registration value"},
    {"id":"purchase_events","label":"Purchase events"},
    {"id":"total_purchase_value","label":"Total purchase value"},
    {"id":"place_an_order_events","label":"Place an order events"},
    {"id":"total_place_an_order_value","label":"Total place an order value"},
    {"id":"search_events","label":"Search events"},{"id":"total_search_value","label":"Total search value"},
    {"id":"download_button_clicks","label":"Download button clicks"},
    {"id":"page_browse_events","label":"Page browse events"},
    {"id":"button_click_events","label":"Button click events"},
    {"id":"total_button_click_value","label":"Total button click value"},
    {"id":"online_consultation_events","label":"Online consultation events"},
    {"id":"total_subscribe","label":"Total subscribe"},
    {"id":"total_subscribe_value","label":"Total subscribe value"},
    {"id":"cost_per_subscribe","label":"Cost per subscribe"},
    {"id":"subscribe_rate","label":"Subscribe rate (%)"},
    {"id":"add_to_wishlist_website","label":"Adds to wishlist (website)"},
    # Onsite
    {"id":"complete_payment_roas_onsite","label":"Complete payment ROAS (onsite)"},
    {"id":"complete_payment_onsite","label":"Complete payment (onsite)"},
    {"id":"total_complete_payment_value_onsite","label":"Total complete payment value (onsite)"},
    {"id":"initiate_checkout_onsite","label":"Initiate checkout (onsite)"},
    {"id":"product_details_page_view_onsite","label":"Product details page view (onsite)"},
    {"id":"add_to_wishlist_onsite","label":"Add to wishlist (onsite)"},
    {"id":"add_billing_onsite","label":"Add billing (onsite)"},
    {"id":"add_to_cart_onsite","label":"Add to cart (onsite)"},
    {"id":"cost_per_add_to_cart_onsite","label":"Cost per add to cart (onsite)"},
    {"id":"form_submission_onsite","label":"Form submission (onsite)"},
    {"id":"app_store_click_onsite","label":"App store click (onsite)"},
    {"id":"total_page_views_onsite","label":"Total page views (onsite)"},
    {"id":"cta_button_clicks_onsite","label":"Call-to-Action button clicks (onsite)"},
    # App
    {"id":"app_installs","label":"App installs"},
    {"id":"real_time_app_installs","label":"Real-time app installs"},
    {"id":"unique_registrations","label":"Unique registrations"},
    {"id":"unique_purchases","label":"Unique purchases"},
    {"id":"unique_adds_to_cart","label":"Unique adds to cart"},
    {"id":"unique_checkouts","label":"Unique checkouts"},
    {"id":"unique_content_views","label":"Unique content views"},
    {"id":"unique_day2_retentions","label":"Unique day 2 retentions"},
    {"id":"unique_payment_info_adds","label":"Unique payment info additions"},
    {"id":"unique_adds_to_wishlist","label":"Unique adds to wishlist"},
    {"id":"unique_app_launches","label":"Unique app launches"},
    {"id":"unique_tutorial_completions","label":"Unique tutorial completions"},
    {"id":"registrations_events","label":"Registrations events"},
    {"id":"checkout_events","label":"Checkout events"},
    {"id":"view_content_events","label":"View content events"},
    {"id":"day2_retention_events","label":"Day 2 retention events"},
    {"id":"add_payment_info_events","label":"Add payment info events"},
    {"id":"launch_app_events","label":"Launch app events"},
    {"id":"in_app_ad_clicks","label":"In-app ad clicks"},
    {"id":"in_app_ad_impressions","label":"In-app ad impressions"},
    {"id":"cost_per_add_to_cart_in_app","label":"Cost per add to cart (in app)"},
    # VTA/CTA
    {"id":"vta_conversions","label":"VTA conversions"},{"id":"vta_registrations","label":"VTA registrations"},
    {"id":"vta_purchases","label":"VTA purchases"},{"id":"cta_conversions","label":"CTA conversions"},
    {"id":"cta_registrations","label":"CTA registrations"},{"id":"cta_purchases","label":"CTA purchases"},
    # SKAN
    {"id":"app_installs_skan","label":"App Installs (SKAN)"},
    {"id":"purchase_events_skan","label":"Purchase events (SKAN)"},
    {"id":"total_purchase_value_skan","label":"Total purchase value (SKAN)"},
    {"id":"add_to_cart_events_skan","label":"Add to cart events (SKAN)"},
    {"id":"checkout_events_skan","label":"Checkout events (SKAN)"},
    {"id":"result_skan","label":"Results (SKAN)"},{"id":"result_rate_skan","label":"Result rate (SKAN)"},
    {"id":"cost_per_result_skan","label":"Cost per result (SKAN)"},
    {"id":"conversions_skan","label":"Conversions (SKAN)"},
    {"id":"conversion_rate_skan","label":"Conversion rate (SKAN)"},
    {"id":"cost_per_conversion_skan","label":"Cost per conversion (SKAN)"},
    # Offline
    {"id":"purchases_offline","label":"Purchases (offline)"},
    {"id":"cost_per_purchase_offline","label":"Cost per purchase (offline)"},
    {"id":"purchase_value_offline","label":"Purchase value (offline)"},
    {"id":"purchase_roas_offline","label":"Purchase ROAS (offline)"},
    {"id":"contacts_offline","label":"Contacts (offline)"},
    {"id":"form_submissions_offline","label":"Form submissions (offline)"},
    {"id":"adds_to_cart_offline","label":"Adds to cart (offline)"},
    {"id":"registrations_offline","label":"Registrations (offline)"},
    {"id":"checkouts_offline","label":"Checkouts initiated (offline)"},
    {"id":"custom_events_offline","label":"Custom events (offline)"},
    {"id":"crm_events","label":"CRM events"},
    {"id":"cost_per_crm_event","label":"Cost per CRM event"},
    {"id":"crm_event_rate","label":"CRM event rate"},
    {"id":"crm_event_value","label":"CRM event value"},
    {"id":"subscriptions_offline","label":"Subscriptions (offline)"},
    {"id":"downloads_offline","label":"Downloads (offline)"},
    {"id":"orders_placed_offline","label":"Orders placed (offline)"},
    {"id":"searches_offline","label":"Searches (offline)"},
    {"id":"content_views_offline","label":"Content views (offline)"},
    {"id":"preferred_leads_offline","label":"Preferred leads (offline)"},
    {"id":"find_location_offline","label":"Total find location (offline)"},
    {"id":"schedule_offline","label":"Total schedule (offline)"},
    {"id":"customize_product_offline","label":"Total customize product (offline)"},
    {"id":"button_clicks_offline","label":"Button clicks (offline)"},
    # Currency variants
    {"id":"cost_eur","label":"Cost (EUR)"},{"id":"cost_gbp","label":"Cost (GBP)"},
    {"id":"cost_usd","label":"Cost (USD)"},
]

DV360_INCOMPAT = [
    # Audience não combina com inventory (doc Bid Manager API)
    ["audience","inventory"],
    # TrueView/YouTube não combina com display standard
    ["trueview","standard"],
    # Audience não combina com geo detalhado
    ["audience","geo"],
]

DV360_DIMENSIONS = [
    # Time
    {"id":"FILTER_DATE","label":"Date"},{"id":"FILTER_WEEK","label":"Week"},
    {"id":"FILTER_MONTH","label":"Month"},{"id":"FILTER_YEAR","label":"Year"},
    {"id":"FILTER_DAY_OF_WEEK","label":"Day of week"},{"id":"FILTER_HOUR_OF_DAY","label":"Hour"},
    {"id":"FILTER_YEAR_MONTH","label":"Year & month"},
    # Account
    {"id":"FILTER_PARTNER","label":"Partner"},{"id":"FILTER_PARTNER_STATUS","label":"Partner status"},
    {"id":"FILTER_ADVERTISER","label":"Advertiser ID"},
    {"id":"FILTER_ADVERTISER_NAME","label":"Advertiser"},
    {"id":"FILTER_ADVERTISER_STATUS","label":"Advertiser status"},
    {"id":"FILTER_ADVERTISER_CURRENCY","label":"Advertiser currency"},
    {"id":"FILTER_ADVERTISER_TIMEZONE","label":"Advertiser timezone"},
    {"id":"FILTER_CAMPAIGN","label":"Campaign"},{"id":"FILTER_CAMPAIGN_ID","label":"Campaign ID"},
    {"id":"FILTER_INSERTION_ORDER","label":"Insertion order ID"},
    {"id":"FILTER_INSERTION_ORDER_NAME","label":"Insertion order"},
    {"id":"FILTER_INSERTION_STATUS","label":"Insertion status"},
    {"id":"FILTER_LINE_ITEM","label":"Line item ID"},
    {"id":"FILTER_LINE_ITEM_NAME","label":"Line item"},
    {"id":"FILTER_LINE_ITEM_STATUS","label":"Line item status"},
    {"id":"FILTER_LINE_ITEM_TYPE","label":"Line item type"},
    # Creative
    {"id":"FILTER_CREATIVE_ID","label":"Creative ID","group":"creative"},
    {"id":"FILTER_CREATIVE","label":"Creative","group":"creative"},
    {"id":"FILTER_CREATIVE_STATUS","label":"Creative status","group":"creative"},
    {"id":"FILTER_CREATIVE_SIZE","label":"Creative size","group":"creative"},
    {"id":"FILTER_CREATIVE_TYPE","label":"Creative type","group":"creative"},
    {"id":"FILTER_MEDIA_TYPE","label":"Media type"},
    # Geo
    {"id":"FILTER_COUNTRY","label":"Country","group":"geo"},
    {"id":"FILTER_REGION","label":"Region","group":"geo"},
    {"id":"FILTER_REGION_ID","label":"Region ID","group":"geo"},
    {"id":"FILTER_CITY","label":"City","group":"geo"},
    {"id":"FILTER_CITY_ID","label":"City ID","group":"geo"},
    {"id":"FILTER_DMA","label":"DMA","group":"geo"},
    {"id":"FILTER_DMA_CODE","label":"DMA code","group":"geo"},
    {"id":"FILTER_ZIP_CODE","label":"Zip code","group":"geo"},
    # Device
    {"id":"FILTER_DEVICE_TYPE","label":"Device type","group":"device"},
    {"id":"FILTER_DEVICE_MAKE","label":"Device make","group":"device"},
    {"id":"FILTER_DEVICE_MODEL","label":"Device model","group":"device"},
    {"id":"FILTER_OPERATING_SYSTEM","label":"Operating system","group":"device"},
    {"id":"FILTER_BROWSER","label":"Browser","group":"device"},
    {"id":"FILTER_CARRIER","label":"Carrier","group":"device"},
    # Inventory
    {"id":"FILTER_SITE_ID","label":"Site","group":"inventory"},
    {"id":"FILTER_APP_URL","label":"App/URL","group":"inventory"},
    {"id":"FILTER_EXCHANGE_ID","label":"Exchange ID","group":"inventory"},
    {"id":"FILTER_EXCHANGE","label":"Exchange","group":"inventory"},
    {"id":"FILTER_INVENTORY_SOURCE","label":"Inventory source","group":"inventory"},
    {"id":"FILTER_INVENTORY_FORMAT","label":"Inventory format","group":"inventory"},
    {"id":"FILTER_INVENTORY_SOURCE_TYPE","label":"Inventory source type","group":"inventory"},
    {"id":"FILTER_PAGE_LAYOUT","label":"Page layout","group":"inventory"},
    {"id":"FILTER_PAGE_CATEGORY","label":"Page category","group":"inventory"},
    # Audience
    {"id":"FILTER_AGE","label":"Age","group":"audience"},
    {"id":"FILTER_GENDER","label":"Gender","group":"audience"},
    # TrueView / YouTube
    {"id":"FILTER_TRUEVIEW_AD_ID","label":"TrueView Ad ID","group":"trueview"},
    {"id":"FILTER_TRUEVIEW_AD_NAME","label":"TrueView Ad name","group":"trueview"},
    {"id":"FILTER_TRUEVIEW_AD_GROUP_ID","label":"TrueView Ad Group ID","group":"trueview"},
    {"id":"FILTER_TRUEVIEW_AD_GROUP_NAME","label":"TrueView Ad Group name","group":"trueview"},
    # Other
    {"id":"FILTER_VIDEO_DURATION","label":"Video duration"},
    {"id":"FILTER_VIDEO_PLAYER_SIZE","label":"Video player size"},
    {"id":"FILTER_AD_POSITION","label":"Ad position"},
    {"id":"FILTER_FLOODLIGHT_ACTIVITY","label":"Floodlight Activity"},
    {"id":"FILTER_KEYWORD","label":"Keyword"},
]

DV360_METRICS = [
    # Core
    {"id":"METRIC_IMPRESSIONS","label":"Impressions"},
    {"id":"METRIC_CLICKS","label":"Clicks"},
    {"id":"METRIC_CTR","label":"CTR"},
    {"id":"METRIC_BILLABLE_IMPRESSIONS","label":"Billable impressions"},
    # Cost
    {"id":"METRIC_MEDIA_COST_ADVERTISER","label":"Media cost (Advertiser)"},
    {"id":"METRIC_TOTAL_MEDIA_COST_ADVERTISER","label":"Total media cost (Advertiser)"},
    {"id":"METRIC_REVENUE_ADVERTISER","label":"Revenue (Advertiser)"},
    {"id":"METRIC_BILLABLE_COST_ADVERTISER","label":"Billable cost (Advertiser)"},
    {"id":"METRIC_PROFIT_ADVERTISER","label":"Profit (Advertiser)"},
    {"id":"METRIC_MEDIA_COST_USD","label":"Media cost (USD)"},
    {"id":"METRIC_REVENUE_USD","label":"Revenue (USD)"},
    {"id":"METRIC_TOTAL_MEDIA_COST_USD","label":"Total media cost (USD)"},
    {"id":"METRIC_MEDIA_COST_ECPM_ADVERTISER","label":"Media cost eCPM (Advertiser)"},
    {"id":"METRIC_MEDIA_COST_ECPC_ADVERTISER","label":"Media cost eCPC (Advertiser)"},
    {"id":"METRIC_REVENUE_ECPM_ADVERTISER","label":"Revenue eCPM (Advertiser)"},
    {"id":"METRIC_REVENUE_ECPC_ADVERTISER","label":"Revenue eCPC (Advertiser)"},
    {"id":"METRIC_PLATFORM_FEE_ADVERTISER","label":"Platform fee (Advertiser)"},
    {"id":"METRIC_CPM_FEE1_ADVERTISER","label":"CPM fee (1) (Advertiser)"},
    # Conversions
    {"id":"METRIC_TOTAL_CONVERSIONS","label":"Total conversions"},
    {"id":"METRIC_LAST_CLICKS","label":"Post-Click Conversions"},
    {"id":"METRIC_LAST_IMPRESSIONS","label":"Post-View Conversions"},
    {"id":"METRIC_TOTAL_CONVERSION_VALUE_ADVERTISER","label":"Total conversion value (Advertiser)"},
    {"id":"METRIC_REVENUE_ECPA_ADVERTISER","label":"Revenue eCPA (Advertiser)"},
    {"id":"METRIC_MEDIA_COST_ECPA_ADVERTISER","label":"Media cost eCPA (Advertiser)"},
    {"id":"METRIC_CONVERSIONS_PER_MILLE","label":"Conversions per mile"},
    {"id":"METRIC_CLICK_TO_POST_CLICK_CONVERSION_RATE","label":"Click to post click conversion rate"},
    # Video
    {"id":"METRIC_RICH_MEDIA_VIDEO_PLAYS","label":"Video plays"},
    {"id":"METRIC_RICH_MEDIA_VIDEO_COMPLETIONS","label":"Video completions"},
    {"id":"METRIC_RICH_MEDIA_VIDEO_FIRST_QUARTILE","label":"Video 1st quartile"},
    {"id":"METRIC_RICH_MEDIA_VIDEO_MIDPOINT","label":"Video midpoint"},
    {"id":"METRIC_RICH_MEDIA_VIDEO_THIRD_QUARTILE","label":"Video 3rd quartile"},
    {"id":"METRIC_RICH_MEDIA_VIDEO_COMPLETION_RATE","label":"Video completion rate"},
    {"id":"METRIC_RICH_MEDIA_VIDEO_PAUSES","label":"Video pauses"},
    {"id":"METRIC_RICH_MEDIA_VIDEO_MUTES","label":"Video mutes"},
    {"id":"METRIC_RICH_MEDIA_VIDEO_FULL_SCREENS","label":"Video full screens"},
    {"id":"METRIC_RICH_MEDIA_VIDEO_SKIP_RATE","label":"Video companion clicks"},
    # Active View
    {"id":"METRIC_ACTIVE_VIEW_VIEWABLE_IMPRESSIONS","label":"Viewable impressions (ActiveView)"},
    {"id":"METRIC_ACTIVE_VIEW_ELIGIBLE_IMPRESSIONS","label":"Eligible impressions (ActiveView)"},
    {"id":"METRIC_ACTIVE_VIEW_MEASURABLE_IMPRESSIONS","label":"Measurable impressions (ActiveView)"},
    {"id":"METRIC_ACTIVE_VIEW_PCT_VIEWABLE_IMPRESSIONS","label":"Viewable impressions % (ActiveView)"},
    {"id":"METRIC_ACTIVE_VIEW_PCT_MEASURABLE_IMPRESSIONS","label":"Measurable impressions % (ActiveView)"},
    {"id":"METRIC_ACTIVE_VIEW_AVERAGE_VIEWABLE_TIME","label":"Average viewable time (ActiveView)"},
    {"id":"METRIC_ACTIVE_VIEW_DISTRIBUTION_VIEWABLE","label":"Distribution viewable % (ActiveView)"},
    # TrueView / YouTube
    {"id":"METRIC_TRUEVIEW_VIEWS","label":"Views"},
    {"id":"METRIC_TRUEVIEW_VIEW_RATE","label":"View rate"},
    {"id":"METRIC_TRUEVIEW_EARNED_LIKES","label":"Earned likes"},
    {"id":"METRIC_TRUEVIEW_EARNED_VIEWS","label":"Earned views"},
    {"id":"METRIC_TRUEVIEW_EARNED_SHARES","label":"Earned shares"},
    {"id":"METRIC_TRUEVIEW_EARNED_SUBSCRIBERS","label":"Earned subscribers"},
    {"id":"METRIC_TRUEVIEW_EARNED_PLAYLIST_ADDITIONS","label":"Earned playlist additions"},
    {"id":"METRIC_TRUEVIEW_VIEW_THROUGH_CONVERSION","label":"View through conversions"},
    {"id":"METRIC_TRUEVIEW_CONVERSIONS","label":"Conversions (TrueView)"},
    {"id":"METRIC_TRUEVIEW_UNIQUE_VIEWERS","label":"Unique viewers"},
    {"id":"METRIC_TRUEVIEW_CPV_ADVERTISER","label":"YouTube: Revenue eCPV (Advertiser)"},
    {"id":"METRIC_TRUEVIEW_CPA_ADVERTISER","label":"YouTube: Cost per conversion (Advertiser)"},
    # Engagements
    {"id":"METRIC_RICH_MEDIA_ENGAGEMENTS","label":"Engagements"},
    {"id":"METRIC_RICH_MEDIA_ENGAGEMENT_RATE","label":"Engagement rate"},
    {"id":"METRIC_RICH_MEDIA_EXPANSIONS","label":"Expansions"},
    {"id":"METRIC_RICH_MEDIA_INTERACTIVE_IMPRESSIONS","label":"Interactive impressions"},
    # Reach
    {"id":"METRIC_UNIQUE_REACH_TOTAL_REACH","label":"Unique reach total reach"},
    {"id":"METRIC_UNIQUE_REACH_IMPRESSION_REACH","label":"Unique reach impression reach"},
    {"id":"METRIC_UNIQUE_REACH_AVERAGE_IMPRESSION_FREQUENCY","label":"Unique reach: average impression frequency"},
]

STATIC = {
    "tiktok": {
        "dimensions": TIKTOK_DIMENSIONS,
        "metrics": TIKTOK_METRICS,
        "incompat": TIKTOK_INCOMPAT
    },
    "dv360": {
        "dimensions": DV360_DIMENSIONS,
        "metrics": DV360_METRICS,
        "incompat": DV360_INCOMPAT
    },
    "kwai": {
        "dimensions": [
            {"id":"date","label":"Date"},{"id":"advertiser_id","label":"Advertiser ID"},
            {"id":"campaign_id","label":"Campaign ID"},{"id":"campaign_name","label":"Campaign name"},
            {"id":"unit_id","label":"Ad Group ID","group":"adgroup"},{"id":"unit_name","label":"Ad Group name","group":"adgroup"},
            {"id":"creative_id","label":"Creative ID","group":"ad"},{"id":"creative_name","label":"Creative name","group":"ad"},
            {"id":"country","label":"Country","group":"geo"},
            {"id":"age","label":"Age","group":"audience"},{"id":"gender","label":"Gender","group":"audience"},
        ],
        "metrics": [
            {"id":"show","label":"Impressions"},{"id":"click","label":"Clicks"},{"id":"charge","label":"Spend"},
            {"id":"avcpm","label":"CPM"},{"id":"ctr","label":"CTR"},{"id":"cpc","label":"CPC"},
            {"id":"play_count","label":"Video Plays"},{"id":"play_3s_count","label":"3s Video Views"},
            {"id":"play_end_count","label":"Video Completions"},{"id":"comment_count","label":"Comments"},
            {"id":"like_count","label":"Likes"},{"id":"share_count","label":"Shares"},{"id":"follow_count","label":"Follows"},
            {"id":"form_count","label":"Form Submissions"},{"id":"conversion_count","label":"Conversions"},
            {"id":"cost_per_convert","label":"Cost per Conversion"},
        ],
        "incompat": [["audience","geo"],["ad","audience"]]
    }
}


class handler(BaseHTTPRequestHandler):
    def do_GET(self):
        qs = parse_qs(urlparse(self.path).query)
        platform = qs.get("platform", [""])[0]
        if not platform:
            self._j({"error": "platform required"}, 400); return
        if platform == "meta":
            self._j({"dimensions": META_DIMENSIONS, "metrics": META_METRICS,
                     "incompat": META_INCOMPAT, "source": "static"})
        else:
            self._j(STATIC.get(platform, {"error": "unknown platform"}))

    def _j(self, data, status=200):
        b = json.dumps(data, default=str).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(b)

app = handler
